version: '2'
services:

  db:
    restart: always
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    ports:
      - "3306"  # docker prefers explicitly stating ports as strings
 
  rabbitmq:
    restart: always
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"

  airflow:
    restart: always
    build:  # configuration options applied at build time
      context: ./airflow
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
      - rabbitmq
    links:
      - db:docker-db
      - rabbitmq:docker-rabbitmq
    command:
      #tail -f /dev/null  # keep container up
      #airflow webserver -p 8080
      /root/airflow/init_script.sh
