version: '2'
services:

  airflow:
    restart: always
    build:  # configuration options applied at build time
      context: ./airflow
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    links:
      - db
    command:
      #tail -f /dev/null  # keep container up
      airflow webserver -p 8080

  db:
    restart: always
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    expose:
      - "3306"