version: '2'
services:

  airflow:
    restart: always
    build:  # configuration options applied at build time
      context: ./airflow
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    command:
      #tail -f /dev/null  # keep container up
      airflow webserver -p 8080

  db:
    restart: always
    image: mysql:5.7
#    environment:
#        MYSQL_ROOT_PASSWORD: root 
    ports:
      - "3306:3306"
  